### ISSUE TITLE
Feature request: color control

### ISSUE THREAD

**Issue by SlimeDog** [Bastian/bStats#144]
It would be nice to be able to configure the color assignments. Something simple, like:
```
colors:
  pie:
    - d44539
    - 8ac76f
    - 6cadfd
    - ecaf32
    - fefb63
    - 65aea0
    - dd3a79
    - 886e62
    - 8195a2
    - 5e6aea
    - 9e6424
    - e05c50
  line:
    - d44539
    - 8ac76f
    - 6cadfd
    - ecaf32
    - fefb63
    - 65aea0
    - dd3a79
    - 886e62
    - 8195a2
    - 5e6aea
    - 9e6424
    - e05c50
  bar:
    - d44539
    - 8ac76f
    - 6cadfd
    - ecaf32
    - fefb63
    - 65aea0
    - dd3a79
    - 886e62
    - 8195a2
    - 5e6aea
    - 9e6424
    - e05c50
  gradient:
    - 9c2221
    - f2cbd0
```
Pie colors could repeat when the list is exhausted, or go random, or whatever. Gradient applies to miscellaneous (ie, maps).
